version: 2
updates:
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: monthly
          day: monday
          time: "12:00"
          timezone: Europe/Berlin
    - package-ecosystem: npm
      directory: "/"
      reviewers:
          - tommycos
      labels:
          - dependencies
      schedule:
          interval: weekly
          day: monday
          time: "12:00"
          timezone: Europe/Berlin
      versioning-strategy: increase
      rebase-strategy: disabled
